version: "3.9"
services:
  core-cart:
    build: .
    command: ./bin/rest-service
    restart: on-failure
    ports:
      - 8915:8080
    environment:
      - APP_ENV=DEVELOPMENT
      - DEBUG=true
      - HTTP_PORT=8080
      - DB_HOST_MYSQL=db-cart
      - DB_PORT_MYSQL=3306
      - DB_USER_MYSQL=root
      - DB_PASSWORD_MYSQL=mauFJcuf5dhRMQrjj
      - DB_NAME_MYSQL=db_cart
      - DB_MAX_IDLE_CONN=10
      - DB_MAX_OPEN_CONN=10
    networks:
      - telkomIndonesia
    depends_on:
      - db-cart

  db-cart:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3388:3306
    environment:
      - MYSQL_DATABASE=db_cart
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - telkomIndonesia

  adminer-cart:
    image: adminer
    restart: always
    ports:
      - 8072:8080
    networks:
      - telkomIndonesia
      
networks:
  telkomIndonesia:
    driver: bridge
